spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agilepm
    username: your_username # Change to your postgres username
    password: your_password # Change to your postgres password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Flyway will handle the schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

